name = "S. C. Arzehd's Galaxy of Games"
author = "scarzehd"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43981e7e12891117ba2b3116fc46d5ed06178fca90816cfa97edf272999d4009"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
